import React from "react";
import Navbar from "../components/navbar";
import Footer from "../components/footer";


export default function about() {
  return (
    <>
      <Navbar />
      <div className="about">
        <h3>About Our Website</h3>
        <p>
          The Carbon Footprint Tracker is an innovative platform designed to
          empower individuals and households in their journey towards a more
          sustainable lifestyle. In an era where climate change poses one of the
          greatest challenges to our planet, understanding and reducing our
          carbon footprint is more critical than ever. This tool provides a
          comprehensive and user-friendly way to track the carbon emissions
          generated by everyday activities, such as energy consumption in your
          home, transportation choices, and waste production. By inputting your
          data into the tracker, you receive a detailed analysis of your
          environmental impact, broken down into easy-to-understand segments.
          <br /> <br />
          Our mission is to make sustainability accessible to everyone,
          regardless of their starting point. The Carbon Footprint Tracker goes
          beyond just numbers; it’s a personalized guide that helps you set
          realistic goals and achieve meaningful reductions in your carbon
          emissions. The platform offers tailored recommendations based on your
          specific lifestyle, providing actionable steps you can take to
          minimize your impact. Whether it’s switching to renewable energy
          sources, adopting more efficient transportation methods, or improving
          waste management practices, the tracker gives you the tools and
          knowledge to make informed decisions that contribute to a healthier
          planet.
          <br /> <br />
          We believe that individual actions, when combined, can lead to
          significant change. The Carbon Footprint Tracker is not just about
          monitoring—it's about inspiring and enabling you to be part of the
          solution to the global climate crisis. By visualizing your progress
          and celebrating your successes, the platform keeps you motivated and
          engaged in the process of becoming more eco-conscious. Join our
          growing community of environmentally aware users who are committed to
          making a difference. Together, we can take concrete steps to reduce
          our collective carbon footprint and pave the way for a sustainable
          future for generations to come.
        </p>
        <h3>Project Members</h3>
        <div className="about-team">
          <ul>
            <li>Manan Hemani - 23BCAR0485</li>
            <li>Tanish Savalia - 23BCAR0486</li>
            <li>Jill Patel - 23BCAR0460</li>
            <li>Spoorthi K B - 23BCAR0480</li>
            <li>Palak R - 23BCAR0464</li>
          </ul>
        </div>
      </div>

      <Footer />
    </>
  );
}
